version: '3.8'

services:
  zwave:
    image: {{ zwave_image }}
    container_name: {{ container_name }}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zwave.rule=Host(`{{ subdomain }}.{{ cluster_domain }}`)"
      - "traefik.http.routers.zwave.entrypoints=websecure"
      - "traefik.http.routers.zwave.tls.certresolver=letsencrypt"
      - "traefik.http.services.zwave.loadbalancer.server.port={{ zwave_frontend_port }}"
    restart: unless-stopped
    tty: true
    stop_signal: SIGINT
    environment:
      - TZ=Europe/Madrid
      - SESSION_SECRET={{ zwave_session_secret }}
      - USE_SECURE_COOKIE=true
      - TRUST_PROXY=true
      - DEFAULT_USERNAME={{ zwave_admin_user }}
      - DEFAULT_PASSWORD={{ zwave_admin_password }}
      - KEY_S0_Legacy={{ zwave_key_s0_legacy }}
      - KEY_S2_Unauthenticated={{ zwave_key_s2_unauthenticated }}
      - KEY_S2_Authenticated={{ zwave_key_s2_authenticated }}
      - KEY_S2_AccessControl={{ zwave_key_s2_accesscontrol }}
      - KEY_LR_S2_Authenticated={{ zwave_key_ls_s2_authenticated }}
      - KEY_LR_S2_AccessControl={{ zwave_key_lr_s2_accesscontrol }}
#    healthcheck:
#      test: 'wget --no-verbose --spider --no-check-certificate --header "Accept: text/plain" http://localhost:8091/health || exit 1'
#      interval: 1m
#      timeout: 10s
#      start_period: 30s
#      retries: 3
    volumes:
{% for volume in volumes %}
      - "{{ volume.src }}:{{ volume.dst }}"
{% endfor %}
    ports:
{% for port in ports %}
      - "{{ port.ext }}:{{ port.int }}"
{% endfor %}
    networks:
      - frontend

networks:
  frontend:
    external: true